#!/usr/bin/env python3
"""
Module 5: Studio 2.0 Export
Exports MOCs to BrickLink Studio .io format with construction steps
"""

import json
from typing import List, Dict
from dataclasses import dataclass


@dataclass
class StudioPart:
    """Part in Studio .io format"""
    part_id: str
    color_id: int
    x: float
    y: float
    z: float
    rotation_matrix: List[float]  # 9 values
    step_number: int = 1


class StudioIOExporter:
    """
    Exports LEGO MOCs to BrickLink Studio 2.0 .io format
    
    Format spec:
    - JSON-based
    - Includes models, bricks, steps, cameras
    - Compatible with Studio 2.0.x
    """
    
    def __init__(self):
        self.format_version = "1.0.0"
        self.studio_version = "2.0"
    
    def create_brick_entry(
        self,
        brick_id: int,
        part: StudioPart
    ) -> Dict:
        """Create a single brick entry for .io format"""
        
        return {
            "brickId": brick_id,
            "designId": part.part_id,
            "materialId": str(part.color_id),
            "position": {
                "x": part.x,
                "y": part.y,
                "z": part.z
            },
            "rotation": {
                "matrix": part.rotation_matrix
            },
            "groupIds": [],
            "customData": {}
        }
    
    def create_step_entry(
        self,
        step_num: int,
        brick_ids: List[int]
    ) -> Dict:
        """Create a construction step entry"""
        
        return {
            "stepNumber": step_num,
            "brickIds": brick_ids,
            "rotation": {
                "x": 0,
                "y": 0,
                "z": 0
            },
            "camera": {
                "distance": 200,
                "latitude": 30,
                "longitude": 45
            }
        }
    
    def export_io(
        self,
        parts: List[StudioPart],
        model_name: str = "Generated MOC",
        author: str = "BrickClinic AI"
    ) -> str:
        """
        Export parts list to Studio .io JSON format
        
        Args:
            parts: List of StudioPart objects
            model_name: Name of the model
            author: Author name
        
        Returns:
            JSON string in .io format
        """
        
        # Group parts by step
        steps_data = {}
        for i, part in enumerate(parts):
            brick_id = i + 1
            step_num = part.step_number
            
            if step_num not in steps_data:
                steps_data[step_num] = []
            
            steps_data[step_num].append((brick_id, part))
        
        # Create brick entries
        bricks = []
        for step_num in sorted(steps_data.keys()):
            for brick_id, part in steps_data[step_num]:
                bricks.append(self.create_brick_entry(brick_id, part))
        
        # Create step entries
        steps = []
        for step_num in sorted(steps_data.keys()):
            brick_ids = [brick_id for brick_id, _ in steps_data[step_num]]
            steps.append(self.create_step_entry(step_num, brick_ids))
        
        # Build complete .io structure
        io_data = {
            "version": self.format_version,
            "meta": {
                "name": model_name,
                "author": author,
                "description": "Generated by BrickClinic DNA-Conditioned System",
                "dateCreated": "",
                "software": f"BrickClinic AI (Studio {self.studio_version} compatible)"
            },
            "models": [
                {
                    "modelId": 1,
                    "name": model_name,
                    "bricks": bricks,
                    "steps": steps,
                    "subModels": [],
                    "groups": []
                }
            ],
            "camera": {
                "distance": 200,
                "latitude": 30,
                "longitude": 45,
                "target": {"x": 0, "y": 0, "z": 0}
            }
        }
        
        return json.dumps(io_data, indent=2)
    
    def export_ldr(
        self,
        parts: List[StudioPart],
        model_name: str = "Generated MOC"
    ) -> str:
        """
        Export to LDraw .ldr format (alternative)
        
        Args:
            parts: List of StudioPart objects
            model_name: Name of the model
        
        Returns:
            LDraw .ldr file content
        """
        
        lines = []
        lines.append(f"0 {model_name}")
        lines.append("0 Name: generated_moc.ldr")
        lines.append("0 Author: BrickClinic AI")
        lines.append("0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt")
        lines.append("")
        
        # Group by steps
        current_step = 1
        for part in sorted(parts, key=lambda p: p.step_number):
            if part.step_number != current_step:
                lines.append(f"0 STEP")
                current_step = part.step_number
            
            # Type 1 line: Part placement
            # Format: 1 <color> <x> <y> <z> <a> <b> <c> <d> <e> <f> <g> <h> <i> <file>
            rotation = part.rotation_matrix
            line = (
                f"1 {part.color_id} "
                f"{part.x:.3f} {part.y:.3f} {part.z:.3f} "
                f"{rotation[0]:.6f} {rotation[1]:.6f} {rotation[2]:.6f} "
                f"{rotation[3]:.6f} {rotation[4]:.6f} {rotation[5]:.6f} "
                f"{rotation[6]:.6f} {rotation[7]:.6f} {rotation[8]:.6f} "
                f"{part.part_id}.dat"
            )
            lines.append(line)
        
        lines.append("0 STEP")
        lines.append("0")
        
        return "\n".join(lines)


def main():
    """Test Studio 2.0 exporter"""
    
    print("🚀 Module 5: Studio 2.0 Export")
    print("=" * 60)
    
    # Create test MOC
    test_parts = [
        StudioPart("300 1", 1, 0, 0, 0, [1,0,0, 0,1,0, 0,0,1], 1),
        StudioPart("3003", 1, 0, -24, 0, [1,0,0, 0,1,0, 0,0,1], 2),
        StudioPart("3020", 14, 0, -48, 0, [1,0,0, 0,1,0, 0,0,1], 3),
    ]
    
    exporter = StudioIOExporter()
    
    # Export to .io format
    print("\n📦 Exporting to Studio .io format...")
    io_content = exporter.export_io(
        test_parts,
        model_name="Test Tower",
        author="BrickClinic AI"
    )
    
    # Save to file
    with open("ai_data/test_moc.io", "w") as f:
        f.write(io_content)
    
    print(f"✅ Saved to ai_data/test_moc.io ({len(io_content)} bytes)")
    
    # Show structure
    io_data = json.loads(io_content)
    print(f"\n📊 Structure:")
    print(f"   Version: {io_data['version']}")
    print(f"   Models: {len(io_data['models'])}")
    print(f"   Bricks: {len(io_data['models'][0]['bricks'])}")
    print(f"   Steps: {len(io_data['models'][0]['steps'])}")
    
    # Export to .ldr format
    print("\n📦 Exporting to LDraw .ldr format...")
    ldr_content = exporter.export_ldr(test_parts, "Test Tower")
    
    with open("ai_data/test_moc.ldr", "w") as f:
        f.write(ldr_content)
    
    print(f"✅ Saved to ai_data/test_moc.ldr ({len(ldr_content)} bytes)")
    print(f"\n📄 Preview:")
    print(ldr_content[:300] + "...")
    
    print("\n" + "=" * 60)
    print("✅ Module 5 Complete!")
    print("   Formats: .io (Studio 2.0) + .ldr (LDraw)")


if __name__ == "__main__":
    main()
